[plugin]
id = "auto-claim"
name = "Auto Claim"
version = "2.1.0"
author = "BambooFury"
description = "Automatically detects 100% discounted games on Steam and adds them to your library."

[assets]
resources = ["LICENSE", ".github/preview.png"]

[backend]
entry = "backend/main.lua"
sources = ["backend/**/*.lua"]

[frontend]
entry = "frontend/index.tsx"

[frontend.globals]
"react" = "window.SP_REACT"

[compiler]
output_path = "auto"
