import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root      = resolve(__dirname, '..');

const stylesDir    = join(root, 'webkit', 'styles');
const templatesDir = join(root, 'webkit', 'templates');
const outPath      = join(root, 'webkit', '_assets.generated.ts');

const css      = readFileSync(join(stylesDir,    'widget.css'),   'utf8');
const widget   = readFileSync(join(templatesDir, 'widget.html'),  'utf8');
const empty    = readFileSync(join(templatesDir, 'empty.html'),   'utf8');
const card     = readFileSync(join(templatesDir, 'card.html'),    'utf8');
const settings = readFileSync(join(templatesDir, 'settings.html'),'utf8');

function asTsLiteral(s) {
  return '`' + s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${') + '`';
}

const banner =
`// AUTO-GENERATED by scripts/build-assets.mjs — DO NOT EDIT BY HAND.
// Source: webkit/styles/widget.css, webkit/templates/*.html
`;

const body =
`export const WIDGET_CSS_TEMPLATE      = ${asTsLiteral(css)};
export const WIDGET_HTML_TEMPLATE     = ${asTsLiteral(widget)};
export const WIDGET_EMPTY_TEMPLATE    = ${asTsLiteral(empty)};
export const WIDGET_CARD_TEMPLATE     = ${asTsLiteral(card)};
export const WIDGET_SETTINGS_TEMPLATE = ${asTsLiteral(settings)};
`;

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, banner + '\n' + body, 'utf8');

console.log(
  `[build-assets] wrote ${outPath}`
  + ` (css: ${css.length}, widget: ${widget.length},`
  + ` empty: ${empty.length}, card: ${card.length}, settings: ${settings.length} chars)`
);
